version: '2'
services:
  mongodb:
    image: mongo:2.4
    container_name: mongodb
    ports:
     - "27017:27017"
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
     - "5672:5672"
     - "15672:15672"
    environment:
     - RABBITMQ_DEFAULT_USER=test
     - RABBITMQ_DEFAULT_PASS=password
  config:
    image: caputomarcos/config-service
    container_name: config
    ports:
     - "8888:8888"
    environment:
     - SPRING_PROFILES_ACTIVE=production
    depends_on:
     - mongodb
     - rabbitmq
  discovery:
    image: caputomarcos/discovery-service
    container_name: discovery
    ports:
     - "8761:8761"
  gateway:
    image: caputomarcos/gateway-service
    container_name: gateway
    ports:
     - "8080:8080"
    environment:
     - SPRING_PROFILES_ACTIVE=production
    depends_on:
     - discovery
     - config
  planet-command-side:
    image: caputomarcos/planet-command-side:latest
    container_name: planet-cmd-side
    depends_on:
     - mongodb
     - rabbitmq
     - discovery
     - config
    ports:
      - "9000"
    environment:
     - SPRING_PROFILES_ACTIVE=production
  planet-query-side:
    image: caputomarcos/planet-query-side:latest
    container_name: planet-qry-side
    depends_on:
     - rabbitmq
     - discovery
     - config
    ports:
     - "9001"
    environment:
     - SPRING_PROFILES_ACTIVE=production
